### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by ker0x** [EmakinaFR/aperitips#20]
Add a CONTRIBUTING.md file with contribution guidelines

# Branches

One branch per issue named with the following pattern:
* Features: `feature/issue-{id}`
* Bugfixes: `hotfix/issue-{id}` or `bugfix/issue-{id}`

ex: `feature/issue-12`, `hotfix/issue-13`

# Commit messages

## What to do ?

When you commit code changes please always add the related Github issue number in the comment. If it's a bug fix you will always have an issue. If not, please create one.

Some basic rules :
* Keep it short: 50 character should be enough
* Summarize the change: what changed in the commit, avoid editorializing
*Be useful: take the time to write something useful, it's time you will spare while reading logs to debug something
* Use English
* Use imperative form (shorter than past form)

A comment template will improve logs readability so you should always use the following pattern:

* `[feature #{id}] commit message`
* `[fix #{id}] commit message`
    
Or the following version if no ticket is available:

* `[n/a] Project initialization`

ex: `[feature #20] add CONTRIBUTING.md`

**Comment by faraazahmad** [comment]
Would it be fine to add the general contribution.md made by Github or do you want custom rules?

**Comment by devshiva619** [comment]
@ker0x I would like to work on this.

**Comment by tannishk** [comment]
see #22
